---
prometheus_node_exporter_version: "0.14.0"
prometheus_node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
prometheus_node_exporter_folder_name: "node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64"
prometheus_node_exporter_enabled_collectors:
  - conntrack
  - diskstats
  - entropy
  - filefd
  - filesystem
  - hwmon
  - loadavg
  - mdadm
  - meminfo
  - netdev
  - netstat
  - stat
  - textfile
  - time
  - vmstat
prometheus_node_exporter_config_parameters:
  'web.listen-address': '0.0.0.0:9100'
  'log.level': 'info'

