---
- name: service reenable
  command: "systemctl reenable {{ prometheus_node_exporter_service_name }}"

- name: restart prometheus node exporter
  service:
    name: "{{ prometheus_node_exporter_service_name }}"
    state: restarted 
